title: goldenxp.com docs
description: >
    Just some random Software Documentation on the Internet
theme: just-the-docs

url: https://docs.goldenxp.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
